// Copy this file to `config.js` and fill in the values for this deployment.
// `config.js` is gitignored so the token does not get committed.
//
// SECURITY NOTE: This token ships to the browser. Use a DEDICATED Monday.com
// user whose access is scoped to ONLY the one board this form targets.
// Anyone with the page URL can read the token from the page source.

const MONDAY_CONFIG = {
  // Monday.com API token for the dedicated, board-scoped user.
  apiToken: "eyJhbGciOiJIUzI1NiJ9.eyJ0aWQiOjY0ODYyNzkzNywiYWFpIjoxMSwidWlkIjo0NDQzMjI4OSwiaWFkIjoiMjAyNi0wNC0yMlQwMjo0NjoxMS4wODdaIiwicGVyIjoibWU6d3JpdGUiLCJhY3RpZCI6OTg3MDE5MiwicmduIjoidXNlMSJ9.EyCuOE6gD7deanVMreuhS6j94Zzx3JS8ubQKevwZPy0",

  // Board ID — from the board URL: monday.com/boards/BOARD_ID
  boardId: "18409668922",

  // Group ID within the board where parent items live.
  // Find via GraphQL: { boards(ids: BOARD_ID) { groups { id title } } }
  groupId: "topics",

  // Column IDs on the SUBITEM board (NOT the parent board).
  // The subitem board is auto-generated by Monday and has its own column IDs.
  // Find them via:
  //   { boards(ids: PARENT_BOARD_ID) {
  //       columns { id title type settings_str }
  //     } }
  // Look for the column of type `subtasks` — its settings_str contains the
  // subitem board ID. Then query that board's columns the same way.
  subitemColumns: {
    // People column for the assignee.
    assignee: "person",

    // Numbers column for the 1-10 rating (NOT Monday's Rating type).
    rating: "numeric_mm2mbqez",

    // Text or long-text column for notes.
    notes: "text_mm2mbk16"
  },

  // Shown at the top of the form.
  formTitle: "Rate the Meeting",

  // Shown below the title.
  formSubtitle: "Please select the meeting and submit your rating."
};
